.TH "Referensi Direktori model/communication" 3 "Rabu 8 Februari 2017" "Version 1.0.2-4" "Sarasvati" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referensi Direktori model/communication
.SH SYNOPSIS
.br
.PP
.SS "File-file"

.in +1c
.ti -1c
.RI "file \fBgprs\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgprs\&.h\fP"
.br
.ti -1c
.RI "file \fBgsm\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgsm\&.h\fP"
.br
.ti -1c
.RI "file \fBserial\&.cpp\fP"
.br
.ti -1c
.RI "file \fBserial\&.h\fP"
.br
.in -1c
