.TH "Referensi Direktori util" 3 "Rabu 8 Februari 2017" "Version 1.0.2-4" "Sarasvati" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referensi Direktori util
.SH SYNOPSIS
.br
.PP
.SS "File-file"

.in +1c
.ti -1c
.RI "file \fBdebug\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdebug\&.h\fP"
.br
.ti -1c
.RI "file \fButama\&.h\fP"
.br
.in -1c
