.TH "Referensi Direktori model" 3 "Rabu 8 Februari 2017" "Version 1.0.2-4" "Sarasvati" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referensi Direktori model
.SH SYNOPSIS
.br
.PP
.SS "Direktori"

.in +1c
.ti -1c
.RI "direktori \fBcommunication\fP"
.br
.ti -1c
.RI "direktori \fBinterface_manipulator\fP"
.br
.in -1c
.SS "File-file"

.in +1c
.ti -1c
.RI "file \fBconfig\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBcryp\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcryp\&.h\fP"
.br
.ti -1c
.RI "file \fBdebug\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdebug\&.h\fP"
.br
.ti -1c
.RI "file \fBmodule\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmodule\&.h\fP"
.br
.ti -1c
.RI "file \fBsetting\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsetting\&.h\fP"
.br
.ti -1c
.RI "file \fButama\&.h\fP"
.br
.in -1c
