.TH "view/formmodule.h" 3 "Rabu 8 Februari 2017" "Version 1.0.2-4" "Sarasvati" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/formmodule.h
.SH SYNOPSIS
.br
.PP
.SS "Struktur Data"

.in +1c
.ti -1c
.RI "class \fBformModule\fP"
.br
.RI "The \fBformModule\fP class\&. "
.in -1c
.SH "Penulis"
.PP 
Dibangkitkan secara otomatis oleh Doxygen untuk Sarasvati dari kode sumber\&.
