.TH "gprs" 3 "Rabu 8 Februari 2017" "Version 1.0.2-4" "Sarasvati" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gprs
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gprs\&.h>\fP
.SS "Fungsi Anggota Publik"
.SH "Keterangan Lengkap"
.PP 
.SH "Dokumentasi Konstruktor & Destruktor"
.PP 
.SS "\fBgprs\fP ()"

.PP
.nf
4 {
5 
6 }
.fi


.SH "Penulis"
.PP 
Dibangkitkan secara otomatis oleh Doxygen untuk Sarasvati dari kode sumber\&.
