.TH "QT_NAMESPACE" 3 "Rabu 8 Februari 2017" "Version 1.0.2-4" "Sarasvati" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QT_NAMESPACE
.SH SYNOPSIS
.br
.PP
.SS "Fungsi"
.SH "Dokumentasi Fungsi"
.PP 
.SS "bool QT_NAMESPACE::qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"

.SS "bool QT_NAMESPACE::qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"

.SH "Penulis"
.PP 
Dibangkitkan secara otomatis oleh Doxygen untuk Sarasvati dari kode sumber\&.
