.TH "controller/worker.h" 3 "Rabu 8 Februari 2017" "Version 1.0.2-4" "Sarasvati" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller/worker.h
.SH SYNOPSIS
.br
.PP
.SS "Struktur Data"

.in +1c
.ti -1c
.RI "class \fBworker\fP"
.br
.RI "Class worker\&. "
.in -1c
.SH "Penulis"
.PP 
Dibangkitkan secara otomatis oleh Doxygen untuk Sarasvati dari kode sumber\&.
